name: 'Publish Sisense dashboards'
description: 'Pulls latest version from master origin'
author: 'N Mehmed'

# Define your inputs here.
inputs:
  token:
    description: 'Sisense API token'
    required: true
  sisenseHost:
    description: 'Sisense Host Url'
    required: true
  projectId:
    description: 'Project id in sisense'
    required: true
  branch:
    description: 'Branch name'
    required: false
    default: 'main'

# Define your outputs here.
# outputs:

runs:
  using: node20
  main: dist/index.js
