name: 'Publish Sisense dashboards'
description: 'Pulls latest version from master origin'
author: 'N Mehmed'

# Define your inputs here.
inputs:
  token:
    description: 'Sisense API token'
    required: true
  sisenseHost:
    description: 'Sisense Host Url'
    required: true
  projectId:
    description: 'Project id in sisense'
    required: true
  branch:
    description: 'Branch name'
    required: false
    default: 'main'
  dashboards:
    description: 'Dashboards to publish, additional to current changes. For multiple dashboards split by space.'
    required: false
  designerToken:
    description: 'Sisense API token which has access to publish dashboards, if it is not provided it will default to token'
    required: false

# Define your outputs here.
# outputs:

runs:
  using: node20
  main: dist/index.js
